// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MqttMessage.proto

package com.xhg.mqtt.mq.proto;

public final class MqttMessagePb {
  private MqttMessagePb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MqttHeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xhg.mqtt.proto.MqttHead)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 指令码
     * </pre>
     *
     * <code>string event_code = 1;</code>
     */
    String getEventCode();
    /**
     * <pre>
     * 指令码
     * </pre>
     *
     * <code>string event_code = 1;</code>
     */
    com.google.protobuf.ByteString
        getEventCodeBytes();

    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string message_id = 2;</code>
     */
    String getMessageId();
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string message_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <pre>
     * 设备id
     * </pre>
     *
     * <code>string device_id = 3;</code>
     */
    String getDeviceId();
    /**
     * <pre>
     * 设备id
     * </pre>
     *
     * <code>string device_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <pre>
     * 版本号
     * </pre>
     *
     * <code>string version = 4;</code>
     */
    String getVersion();
    /**
     * <pre>
     * 版本号
     * </pre>
     *
     * <code>string version = 4;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     * 状态码 0:失败 1:成功
     * </pre>
     *
     * <code>int32 result_code = 5;</code>
     */
    int getResultCode();

    /**
     * <pre>
     * 状态码描述
     * </pre>
     *
     * <code>string result_desc = 6;</code>
     */
    String getResultDesc();
    /**
     * <pre>
     * 状态码描述
     * </pre>
     *
     * <code>string result_desc = 6;</code>
     */
    com.google.protobuf.ByteString
        getResultDescBytes();

    /**
     * <pre>
     * 控制码（转成二进制00000000, 1位代表一种控制, 0:关闭, 1:开启, 第1位代表ACK, 当ack开启时, 此指令需要回馈,其余预留）
     * </pre>
     *
     * <code>int32 cc = 7;</code>
     */
    int getCc();
  }
  /**
   * <pre>
   * 协议请求头
   * </pre>
   *
   * Protobuf type {@code com.xhg.mqtt.proto.MqttHead}
   */
  public  static final class MqttHead extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xhg.mqtt.proto.MqttHead)
      MqttHeadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MqttHead.newBuilder() to construct.
    private MqttHead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MqttHead() {
      eventCode_ = "";
      messageId_ = "";
      deviceId_ = "";
      version_ = "";
      resultCode_ = 0;
      resultDesc_ = "";
      cc_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MqttHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              eventCode_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 40: {

              resultCode_ = input.readInt32();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              resultDesc_ = s;
              break;
            }
            case 56: {

              cc_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MqttMessagePb.internal_static_com_xhg_mqtt_proto_MqttHead_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MqttMessagePb.internal_static_com_xhg_mqtt_proto_MqttHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MqttHead.class, Builder.class);
    }

    public static final int EVENT_CODE_FIELD_NUMBER = 1;
    private volatile Object eventCode_;
    /**
     * <pre>
     * 指令码
     * </pre>
     *
     * <code>string event_code = 1;</code>
     */
    public String getEventCode() {
      Object ref = eventCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        eventCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 指令码
     * </pre>
     *
     * <code>string event_code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEventCodeBytes() {
      Object ref = eventCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        eventCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 2;
    private volatile Object messageId_;
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string message_id = 2;</code>
     */
    public String getMessageId() {
      Object ref = messageId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string message_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_ID_FIELD_NUMBER = 3;
    private volatile Object deviceId_;
    /**
     * <pre>
     * 设备id
     * </pre>
     *
     * <code>string device_id = 3;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 设备id
     * </pre>
     *
     * <code>string device_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private volatile Object version_;
    /**
     * <pre>
     * 版本号
     * </pre>
     *
     * <code>string version = 4;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 版本号
     * </pre>
     *
     * <code>string version = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_CODE_FIELD_NUMBER = 5;
    private int resultCode_;
    /**
     * <pre>
     * 状态码 0:失败 1:成功
     * </pre>
     *
     * <code>int32 result_code = 5;</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    public static final int RESULT_DESC_FIELD_NUMBER = 6;
    private volatile Object resultDesc_;
    /**
     * <pre>
     * 状态码描述
     * </pre>
     *
     * <code>string result_desc = 6;</code>
     */
    public String getResultDesc() {
      Object ref = resultDesc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        resultDesc_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 状态码描述
     * </pre>
     *
     * <code>string result_desc = 6;</code>
     */
    public com.google.protobuf.ByteString
        getResultDescBytes() {
      Object ref = resultDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        resultDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CC_FIELD_NUMBER = 7;
    private int cc_;
    /**
     * <pre>
     * 控制码（转成二进制00000000, 1位代表一种控制, 0:关闭, 1:开启, 第1位代表ACK, 当ack开启时, 此指令需要回馈,其余预留）
     * </pre>
     *
     * <code>int32 cc = 7;</code>
     */
    public int getCc() {
      return cc_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEventCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventCode_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messageId_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceId_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, version_);
      }
      if (resultCode_ != 0) {
        output.writeInt32(5, resultCode_);
      }
      if (!getResultDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, resultDesc_);
      }
      if (cc_ != 0) {
        output.writeInt32(7, cc_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEventCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventCode_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messageId_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceId_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, version_);
      }
      if (resultCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, resultCode_);
      }
      if (!getResultDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, resultDesc_);
      }
      if (cc_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, cc_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MqttHead)) {
        return super.equals(obj);
      }
      MqttHead other = (MqttHead) obj;

      boolean result = true;
      result = result && getEventCode()
          .equals(other.getEventCode());
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && (getResultCode()
          == other.getResultCode());
      result = result && getResultDesc()
          .equals(other.getResultDesc());
      result = result && (getCc()
          == other.getCc());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENT_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getEventCode().hashCode();
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + RESULT_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getResultCode();
      hash = (37 * hash) + RESULT_DESC_FIELD_NUMBER;
      hash = (53 * hash) + getResultDesc().hashCode();
      hash = (37 * hash) + CC_FIELD_NUMBER;
      hash = (53 * hash) + getCc();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MqttHead parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MqttHead parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MqttHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MqttHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MqttHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MqttHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MqttHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MqttHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MqttHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MqttHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MqttHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MqttHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MqttHead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 协议请求头
     * </pre>
     *
     * Protobuf type {@code com.xhg.mqtt.proto.MqttHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xhg.mqtt.proto.MqttHead)
        MqttHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MqttMessagePb.internal_static_com_xhg_mqtt_proto_MqttHead_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MqttMessagePb.internal_static_com_xhg_mqtt_proto_MqttHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MqttHead.class, Builder.class);
      }

      // Construct using com.xhg.mqtt.proto.MqttMessagePb.MqttHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        eventCode_ = "";

        messageId_ = "";

        deviceId_ = "";

        version_ = "";

        resultCode_ = 0;

        resultDesc_ = "";

        cc_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MqttMessagePb.internal_static_com_xhg_mqtt_proto_MqttHead_descriptor;
      }

      @Override
      public MqttHead getDefaultInstanceForType() {
        return MqttHead.getDefaultInstance();
      }

      @Override
      public MqttHead build() {
        MqttHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MqttHead buildPartial() {
        MqttHead result = new MqttHead(this);
        result.eventCode_ = eventCode_;
        result.messageId_ = messageId_;
        result.deviceId_ = deviceId_;
        result.version_ = version_;
        result.resultCode_ = resultCode_;
        result.resultDesc_ = resultDesc_;
        result.cc_ = cc_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MqttHead) {
          return mergeFrom((MqttHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MqttHead other) {
        if (other == MqttHead.getDefaultInstance()) return this;
        if (!other.getEventCode().isEmpty()) {
          eventCode_ = other.eventCode_;
          onChanged();
        }
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.getResultCode() != 0) {
          setResultCode(other.getResultCode());
        }
        if (!other.getResultDesc().isEmpty()) {
          resultDesc_ = other.resultDesc_;
          onChanged();
        }
        if (other.getCc() != 0) {
          setCc(other.getCc());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MqttHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MqttHead) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object eventCode_ = "";
      /**
       * <pre>
       * 指令码
       * </pre>
       *
       * <code>string event_code = 1;</code>
       */
      public String getEventCode() {
        Object ref = eventCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          eventCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 指令码
       * </pre>
       *
       * <code>string event_code = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEventCodeBytes() {
        Object ref = eventCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          eventCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 指令码
       * </pre>
       *
       * <code>string event_code = 1;</code>
       */
      public Builder setEventCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 指令码
       * </pre>
       *
       * <code>string event_code = 1;</code>
       */
      public Builder clearEventCode() {
        
        eventCode_ = getDefaultInstance().getEventCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 指令码
       * </pre>
       *
       * <code>string event_code = 1;</code>
       */
      public Builder setEventCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventCode_ = value;
        onChanged();
        return this;
      }

      private Object messageId_ = "";
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string message_id = 2;</code>
       */
      public String getMessageId() {
        Object ref = messageId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string message_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string message_id = 2;</code>
       */
      public Builder setMessageId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string message_id = 2;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string message_id = 2;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private Object deviceId_ = "";
      /**
       * <pre>
       * 设备id
       * </pre>
       *
       * <code>string device_id = 3;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 设备id
       * </pre>
       *
       * <code>string device_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 设备id
       * </pre>
       *
       * <code>string device_id = 3;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备id
       * </pre>
       *
       * <code>string device_id = 3;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备id
       * </pre>
       *
       * <code>string device_id = 3;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <pre>
       * 版本号
       * </pre>
       *
       * <code>string version = 4;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 版本号
       * </pre>
       *
       * <code>string version = 4;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 版本号
       * </pre>
       *
       * <code>string version = 4;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 版本号
       * </pre>
       *
       * <code>string version = 4;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 版本号
       * </pre>
       *
       * <code>string version = 4;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private int resultCode_ ;
      /**
       * <pre>
       * 状态码 0:失败 1:成功
       * </pre>
       *
       * <code>int32 result_code = 5;</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <pre>
       * 状态码 0:失败 1:成功
       * </pre>
       *
       * <code>int32 result_code = 5;</code>
       */
      public Builder setResultCode(int value) {
        
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态码 0:失败 1:成功
       * </pre>
       *
       * <code>int32 result_code = 5;</code>
       */
      public Builder clearResultCode() {
        
        resultCode_ = 0;
        onChanged();
        return this;
      }

      private Object resultDesc_ = "";
      /**
       * <pre>
       * 状态码描述
       * </pre>
       *
       * <code>string result_desc = 6;</code>
       */
      public String getResultDesc() {
        Object ref = resultDesc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          resultDesc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 状态码描述
       * </pre>
       *
       * <code>string result_desc = 6;</code>
       */
      public com.google.protobuf.ByteString
          getResultDescBytes() {
        Object ref = resultDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          resultDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 状态码描述
       * </pre>
       *
       * <code>string result_desc = 6;</code>
       */
      public Builder setResultDesc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resultDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态码描述
       * </pre>
       *
       * <code>string result_desc = 6;</code>
       */
      public Builder clearResultDesc() {
        
        resultDesc_ = getDefaultInstance().getResultDesc();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态码描述
       * </pre>
       *
       * <code>string result_desc = 6;</code>
       */
      public Builder setResultDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resultDesc_ = value;
        onChanged();
        return this;
      }

      private int cc_ ;
      /**
       * <pre>
       * 控制码（转成二进制00000000, 1位代表一种控制, 0:关闭, 1:开启, 第1位代表ACK, 当ack开启时, 此指令需要回馈,其余预留）
       * </pre>
       *
       * <code>int32 cc = 7;</code>
       */
      public int getCc() {
        return cc_;
      }
      /**
       * <pre>
       * 控制码（转成二进制00000000, 1位代表一种控制, 0:关闭, 1:开启, 第1位代表ACK, 当ack开启时, 此指令需要回馈,其余预留）
       * </pre>
       *
       * <code>int32 cc = 7;</code>
       */
      public Builder setCc(int value) {
        
        cc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 控制码（转成二进制00000000, 1位代表一种控制, 0:关闭, 1:开启, 第1位代表ACK, 当ack开启时, 此指令需要回馈,其余预留）
       * </pre>
       *
       * <code>int32 cc = 7;</code>
       */
      public Builder clearCc() {
        
        cc_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xhg.mqtt.proto.MqttHead)
    }

    // @@protoc_insertion_point(class_scope:com.xhg.mqtt.proto.MqttHead)
    private static final MqttHead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MqttHead();
    }

    public static MqttHead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MqttHead>
        PARSER = new com.google.protobuf.AbstractParser<MqttHead>() {
      @Override
      public MqttHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MqttHead(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MqttHead> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MqttHead> getParserForType() {
      return PARSER;
    }

    @Override
    public MqttHead getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MqttMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xhg.mqtt.proto.MqttMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
     */
    boolean hasHead();
    /**
     * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
     */
    MqttHead getHead();
    /**
     * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
     */
    MqttHeadOrBuilder getHeadOrBuilder();

    /**
     * <code>bytes body = 2;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * <pre>
   * 消息主体
   * </pre>
   *
   * Protobuf type {@code com.xhg.mqtt.proto.MqttMessage}
   */
  public  static final class MqttMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xhg.mqtt.proto.MqttMessage)
      MqttMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MqttMessage.newBuilder() to construct.
    private MqttMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MqttMessage() {
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MqttMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              MqttHead.Builder subBuilder = null;
              if (head_ != null) {
                subBuilder = head_.toBuilder();
              }
              head_ = input.readMessage(MqttHead.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(head_);
                head_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MqttMessagePb.internal_static_com_xhg_mqtt_proto_MqttMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MqttMessagePb.internal_static_com_xhg_mqtt_proto_MqttMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MqttMessage.class, Builder.class);
    }

    public static final int HEAD_FIELD_NUMBER = 1;
    private MqttHead head_;
    /**
     * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
     */
    public boolean hasHead() {
      return head_ != null;
    }
    /**
     * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
     */
    public MqttHead getHead() {
      return head_ == null ? MqttHead.getDefaultInstance() : head_;
    }
    /**
     * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
     */
    public MqttHeadOrBuilder getHeadOrBuilder() {
      return getHead();
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 2;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (head_ != null) {
        output.writeMessage(1, getHead());
      }
      if (!body_.isEmpty()) {
        output.writeBytes(2, body_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (head_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHead());
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MqttMessage)) {
        return super.equals(obj);
      }
      MqttMessage other = (MqttMessage) obj;

      boolean result = true;
      result = result && (hasHead() == other.hasHead());
      if (hasHead()) {
        result = result && getHead()
            .equals(other.getHead());
      }
      result = result && getBody()
          .equals(other.getBody());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHead()) {
        hash = (37 * hash) + HEAD_FIELD_NUMBER;
        hash = (53 * hash) + getHead().hashCode();
      }
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MqttMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MqttMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MqttMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MqttMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MqttMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MqttMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MqttMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MqttMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MqttMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MqttMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MqttMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MqttMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MqttMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 消息主体
     * </pre>
     *
     * Protobuf type {@code com.xhg.mqtt.proto.MqttMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xhg.mqtt.proto.MqttMessage)
        MqttMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MqttMessagePb.internal_static_com_xhg_mqtt_proto_MqttMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MqttMessagePb.internal_static_com_xhg_mqtt_proto_MqttMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MqttMessage.class, Builder.class);
      }

      // Construct using com.xhg.mqtt.proto.MqttMessagePb.MqttMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (headBuilder_ == null) {
          head_ = null;
        } else {
          head_ = null;
          headBuilder_ = null;
        }
        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MqttMessagePb.internal_static_com_xhg_mqtt_proto_MqttMessage_descriptor;
      }

      @Override
      public MqttMessage getDefaultInstanceForType() {
        return MqttMessage.getDefaultInstance();
      }

      @Override
      public MqttMessage build() {
        MqttMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MqttMessage buildPartial() {
        MqttMessage result = new MqttMessage(this);
        if (headBuilder_ == null) {
          result.head_ = head_;
        } else {
          result.head_ = headBuilder_.build();
        }
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MqttMessage) {
          return mergeFrom((MqttMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MqttMessage other) {
        if (other == MqttMessage.getDefaultInstance()) return this;
        if (other.hasHead()) {
          mergeHead(other.getHead());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MqttMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MqttMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private MqttHead head_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          MqttHead, MqttHead.Builder, MqttHeadOrBuilder> headBuilder_;
      /**
       * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
       */
      public boolean hasHead() {
        return headBuilder_ != null || head_ != null;
      }
      /**
       * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
       */
      public MqttHead getHead() {
        if (headBuilder_ == null) {
          return head_ == null ? MqttHead.getDefaultInstance() : head_;
        } else {
          return headBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
       */
      public Builder setHead(MqttHead value) {
        if (headBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          head_ = value;
          onChanged();
        } else {
          headBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
       */
      public Builder setHead(
          MqttHead.Builder builderForValue) {
        if (headBuilder_ == null) {
          head_ = builderForValue.build();
          onChanged();
        } else {
          headBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
       */
      public Builder mergeHead(MqttHead value) {
        if (headBuilder_ == null) {
          if (head_ != null) {
            head_ =
              MqttHead.newBuilder(head_).mergeFrom(value).buildPartial();
          } else {
            head_ = value;
          }
          onChanged();
        } else {
          headBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
       */
      public Builder clearHead() {
        if (headBuilder_ == null) {
          head_ = null;
          onChanged();
        } else {
          head_ = null;
          headBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
       */
      public MqttHead.Builder getHeadBuilder() {
        
        onChanged();
        return getHeadFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
       */
      public MqttHeadOrBuilder getHeadOrBuilder() {
        if (headBuilder_ != null) {
          return headBuilder_.getMessageOrBuilder();
        } else {
          return head_ == null ?
              MqttHead.getDefaultInstance() : head_;
        }
      }
      /**
       * <code>.com.xhg.mqtt.proto.MqttHead head = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MqttHead, MqttHead.Builder, MqttHeadOrBuilder>
          getHeadFieldBuilder() {
        if (headBuilder_ == null) {
          headBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MqttHead, MqttHead.Builder, MqttHeadOrBuilder>(
                  getHead(),
                  getParentForChildren(),
                  isClean());
          head_ = null;
        }
        return headBuilder_;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 2;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 2;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xhg.mqtt.proto.MqttMessage)
    }

    // @@protoc_insertion_point(class_scope:com.xhg.mqtt.proto.MqttMessage)
    private static final MqttMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MqttMessage();
    }

    public static MqttMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MqttMessage>
        PARSER = new com.google.protobuf.AbstractParser<MqttMessage>() {
      @Override
      public MqttMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MqttMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MqttMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MqttMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public MqttMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xhg_mqtt_proto_MqttHead_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xhg_mqtt_proto_MqttHead_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xhg_mqtt_proto_MqttMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xhg_mqtt_proto_MqttMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021MqttMessage.proto\022\022com.xhg.mqtt.proto\"" +
      "\214\001\n\010MqttHead\022\022\n\nevent_code\030\001 \001(\t\022\022\n\nmess" +
      "age_id\030\002 \001(\t\022\021\n\tdevice_id\030\003 \001(\t\022\017\n\007versi" +
      "on\030\004 \001(\t\022\023\n\013result_code\030\005 \001(\005\022\023\n\013result_" +
      "desc\030\006 \001(\t\022\n\n\002cc\030\007 \001(\005\"G\n\013MqttMessage\022*\n" +
      "\004head\030\001 \001(\0132\034.com.xhg.mqtt.proto.MqttHea" +
      "d\022\014\n\004body\030\002 \001(\014B\017B\rMqttMessagePbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xhg_mqtt_proto_MqttHead_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xhg_mqtt_proto_MqttHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xhg_mqtt_proto_MqttHead_descriptor,
        new String[] { "EventCode", "MessageId", "DeviceId", "Version", "ResultCode", "ResultDesc", "Cc", });
    internal_static_com_xhg_mqtt_proto_MqttMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xhg_mqtt_proto_MqttMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xhg_mqtt_proto_MqttMessage_descriptor,
        new String[] { "Head", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
