// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BoxInfo.proto

package com.eve.mqtt.common.proto;

public final class BoxInfoPb {
  private BoxInfoPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BoxInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xhg.mqtt.proto.BoxInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
     */
    java.util.List<BoxStatus>
        getBoxStatusList();
    /**
     * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
     */
    BoxStatus getBoxStatus(int index);
    /**
     * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
     */
    int getBoxStatusCount();
    /**
     * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
     */
    java.util.List<? extends BoxStatusOrBuilder>
        getBoxStatusOrBuilderList();
    /**
     * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
     */
    BoxStatusOrBuilder getBoxStatusOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.xhg.mqtt.proto.BoxInfo}
   */
  public  static final class BoxInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xhg.mqtt.proto.BoxInfo)
      BoxInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BoxInfo.newBuilder() to construct.
    private BoxInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BoxInfo() {
      boxStatus_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BoxInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                boxStatus_ = new java.util.ArrayList<BoxStatus>();
                mutable_bitField0_ |= 0x00000001;
              }
              boxStatus_.add(
                  input.readMessage(BoxStatus.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          boxStatus_ = java.util.Collections.unmodifiableList(boxStatus_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BoxInfoPb.internal_static_com_xhg_mqtt_proto_BoxInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BoxInfoPb.internal_static_com_xhg_mqtt_proto_BoxInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BoxInfo.class, Builder.class);
    }

    public static final int BOXSTATUS_FIELD_NUMBER = 1;
    private java.util.List<BoxStatus> boxStatus_;
    /**
     * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
     */
    @Override
    public java.util.List<BoxStatus> getBoxStatusList() {
      return boxStatus_;
    }
    /**
     * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
     */
    @Override
    public java.util.List<? extends BoxStatusOrBuilder>
        getBoxStatusOrBuilderList() {
      return boxStatus_;
    }
    /**
     * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
     */
    @Override
    public int getBoxStatusCount() {
      return boxStatus_.size();
    }
    /**
     * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
     */
    @Override
    public BoxStatus getBoxStatus(int index) {
      return boxStatus_.get(index);
    }
    /**
     * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
     */
    @Override
    public BoxStatusOrBuilder getBoxStatusOrBuilder(
        int index) {
      return boxStatus_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
          return true;
      }
      if (isInitialized == 0) {
          return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < boxStatus_.size(); i++) {
        output.writeMessage(1, boxStatus_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
          return size;
      }

      size = 0;
      for (int i = 0; i < boxStatus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, boxStatus_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BoxInfo)) {
        return super.equals(obj);
      }
      BoxInfo other = (BoxInfo) obj;

      boolean result = true;
      result = result && getBoxStatusList()
          .equals(other.getBoxStatusList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBoxStatusCount() > 0) {
        hash = (37 * hash) + BOXSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getBoxStatusList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BoxInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoxInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoxInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoxInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoxInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoxInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoxInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BoxInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BoxInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BoxInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BoxInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BoxInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BoxInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xhg.mqtt.proto.BoxInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xhg.mqtt.proto.BoxInfo)
        BoxInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BoxInfoPb.internal_static_com_xhg_mqtt_proto_BoxInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BoxInfoPb.internal_static_com_xhg_mqtt_proto_BoxInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BoxInfo.class, Builder.class);
      }

      // Construct using com.xhg.mqtt.proto.BoxInfoPb.BoxInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBoxStatusFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (boxStatusBuilder_ == null) {
          boxStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          boxStatusBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BoxInfoPb.internal_static_com_xhg_mqtt_proto_BoxInfo_descriptor;
      }

      @Override
      public BoxInfo getDefaultInstanceForType() {
        return BoxInfo.getDefaultInstance();
      }

      @Override
      public BoxInfo build() {
        BoxInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BoxInfo buildPartial() {
        BoxInfo result = new BoxInfo(this);
        int from_bitField0_ = bitField0_;
        if (boxStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            boxStatus_ = java.util.Collections.unmodifiableList(boxStatus_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.boxStatus_ = boxStatus_;
        } else {
          result.boxStatus_ = boxStatusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BoxInfo) {
          return mergeFrom((BoxInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BoxInfo other) {
        if (other == BoxInfo.getDefaultInstance()) {
            return this;
        }
        if (boxStatusBuilder_ == null) {
          if (!other.boxStatus_.isEmpty()) {
            if (boxStatus_.isEmpty()) {
              boxStatus_ = other.boxStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBoxStatusIsMutable();
              boxStatus_.addAll(other.boxStatus_);
            }
            onChanged();
          }
        } else {
          if (!other.boxStatus_.isEmpty()) {
            if (boxStatusBuilder_.isEmpty()) {
              boxStatusBuilder_.dispose();
              boxStatusBuilder_ = null;
              boxStatus_ = other.boxStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
              boxStatusBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBoxStatusFieldBuilder() : null;
            } else {
              boxStatusBuilder_.addAllMessages(other.boxStatus_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BoxInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BoxInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<BoxStatus> boxStatus_ =
        java.util.Collections.emptyList();
      private void ensureBoxStatusIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          boxStatus_ = new java.util.ArrayList<BoxStatus>(boxStatus_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          BoxStatus, BoxStatus.Builder, BoxStatusOrBuilder> boxStatusBuilder_;

      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      @Override
      public java.util.List<BoxStatus> getBoxStatusList() {
        if (boxStatusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(boxStatus_);
        } else {
          return boxStatusBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      @Override
      public int getBoxStatusCount() {
        if (boxStatusBuilder_ == null) {
          return boxStatus_.size();
        } else {
          return boxStatusBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      @Override
      public BoxStatus getBoxStatus(int index) {
        if (boxStatusBuilder_ == null) {
          return boxStatus_.get(index);
        } else {
          return boxStatusBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public Builder setBoxStatus(
          int index, BoxStatus value) {
        if (boxStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoxStatusIsMutable();
          boxStatus_.set(index, value);
          onChanged();
        } else {
          boxStatusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public Builder setBoxStatus(
          int index, BoxStatus.Builder builderForValue) {
        if (boxStatusBuilder_ == null) {
          ensureBoxStatusIsMutable();
          boxStatus_.set(index, builderForValue.build());
          onChanged();
        } else {
          boxStatusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public Builder addBoxStatus(BoxStatus value) {
        if (boxStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoxStatusIsMutable();
          boxStatus_.add(value);
          onChanged();
        } else {
          boxStatusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public Builder addBoxStatus(
          int index, BoxStatus value) {
        if (boxStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoxStatusIsMutable();
          boxStatus_.add(index, value);
          onChanged();
        } else {
          boxStatusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public Builder addBoxStatus(
          BoxStatus.Builder builderForValue) {
        if (boxStatusBuilder_ == null) {
          ensureBoxStatusIsMutable();
          boxStatus_.add(builderForValue.build());
          onChanged();
        } else {
          boxStatusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public Builder addBoxStatus(
          int index, BoxStatus.Builder builderForValue) {
        if (boxStatusBuilder_ == null) {
          ensureBoxStatusIsMutable();
          boxStatus_.add(index, builderForValue.build());
          onChanged();
        } else {
          boxStatusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public Builder addAllBoxStatus(
          Iterable<? extends BoxStatus> values) {
        if (boxStatusBuilder_ == null) {
          ensureBoxStatusIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, boxStatus_);
          onChanged();
        } else {
          boxStatusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public Builder clearBoxStatus() {
        if (boxStatusBuilder_ == null) {
          boxStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          boxStatusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public Builder removeBoxStatus(int index) {
        if (boxStatusBuilder_ == null) {
          ensureBoxStatusIsMutable();
          boxStatus_.remove(index);
          onChanged();
        } else {
          boxStatusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public BoxStatus.Builder getBoxStatusBuilder(
          int index) {
        return getBoxStatusFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      @Override
      public BoxStatusOrBuilder getBoxStatusOrBuilder(
          int index) {
        if (boxStatusBuilder_ == null) {
          return boxStatus_.get(index);  } else {
          return boxStatusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      @Override
      public java.util.List<? extends BoxStatusOrBuilder>
           getBoxStatusOrBuilderList() {
        if (boxStatusBuilder_ != null) {
          return boxStatusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(boxStatus_);
        }
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public BoxStatus.Builder addBoxStatusBuilder() {
        return getBoxStatusFieldBuilder().addBuilder(
            BoxStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public BoxStatus.Builder addBoxStatusBuilder(
          int index) {
        return getBoxStatusFieldBuilder().addBuilder(
            index, BoxStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.BoxStatus boxStatus = 1;</code>
       */
      public java.util.List<BoxStatus.Builder>
           getBoxStatusBuilderList() {
        return getBoxStatusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          BoxStatus, BoxStatus.Builder, BoxStatusOrBuilder>
          getBoxStatusFieldBuilder() {
        if (boxStatusBuilder_ == null) {
          boxStatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              BoxStatus, BoxStatus.Builder, BoxStatusOrBuilder>(
                  boxStatus_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          boxStatus_ = null;
        }
        return boxStatusBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xhg.mqtt.proto.BoxInfo)
    }

    // @@protoc_insertion_point(class_scope:com.xhg.mqtt.proto.BoxInfo)
    private static final BoxInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BoxInfo();
    }

    public static BoxInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BoxInfo>
        PARSER = new com.google.protobuf.AbstractParser<BoxInfo>() {
      @Override
      public BoxInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BoxInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BoxInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BoxInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public BoxInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BoxStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xhg.mqtt.proto.BoxStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 box_status = 1;</code>
     */
    int getBoxStatus();

    /**
     * <code>int32 type = 2;</code>
     */
    int getType();

    /**
     * <code>int32 except_status = 3;</code>
     */
    int getExceptStatus();

    /**
     * <code>double load_rate = 4;</code>
     */
    double getLoadRate();

    /**
     * <code>int32 sterilize_status = 5;</code>
     */
    int getSterilizeStatus();

    /**
     * <code>repeated int32 error_code = 6;</code>
     */
    java.util.List<Integer> getErrorCodeList();
    /**
     * <code>repeated int32 error_code = 6;</code>
     */
    int getErrorCodeCount();
    /**
     * <code>repeated int32 error_code = 6;</code>
     */
    int getErrorCode(int index);

    /**
     * <code>double temperature = 7;</code>
     */
    double getTemperature();

    /**
     * <code>int32 trace = 8;</code>
     */
    int getTrace();

    /**
     * <code>double total_weight = 9;</code>
     */
    double getTotalWeight();

    /**
     * <code>int32 work_type = 10;</code>
     */
    int getWorkType();
  }
  /**
   * Protobuf type {@code com.xhg.mqtt.proto.BoxStatus}
   */
  public  static final class BoxStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xhg.mqtt.proto.BoxStatus)
      BoxStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BoxStatus.newBuilder() to construct.
    private BoxStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BoxStatus() {
      boxStatus_ = 0;
      type_ = 0;
      exceptStatus_ = 0;
      loadRate_ = 0D;
      sterilizeStatus_ = 0;
      errorCode_ = java.util.Collections.emptyList();
      temperature_ = 0D;
      trace_ = 0;
      totalWeight_ = 0D;
      workType_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BoxStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              boxStatus_ = input.readInt32();
              break;
            }
            case 16: {

              type_ = input.readInt32();
              break;
            }
            case 24: {

              exceptStatus_ = input.readInt32();
              break;
            }
            case 33: {

              loadRate_ = input.readDouble();
              break;
            }
            case 40: {

              sterilizeStatus_ = input.readInt32();
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                errorCode_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              errorCode_.add(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                errorCode_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                errorCode_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 57: {

              temperature_ = input.readDouble();
              break;
            }
            case 64: {

              trace_ = input.readInt32();
              break;
            }
            case 73: {

              totalWeight_ = input.readDouble();
              break;
            }
            case 80: {

              workType_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          errorCode_ = java.util.Collections.unmodifiableList(errorCode_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BoxInfoPb.internal_static_com_xhg_mqtt_proto_BoxStatus_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BoxInfoPb.internal_static_com_xhg_mqtt_proto_BoxStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BoxStatus.class, Builder.class);
    }

    private int bitField0_;
    public static final int BOX_STATUS_FIELD_NUMBER = 1;
    private int boxStatus_;
    /**
     * <code>int32 box_status = 1;</code>
     */
    @Override
    public int getBoxStatus() {
      return boxStatus_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>int32 type = 2;</code>
     */
    @Override
    public int getType() {
      return type_;
    }

    public static final int EXCEPT_STATUS_FIELD_NUMBER = 3;
    private int exceptStatus_;
    /**
     * <code>int32 except_status = 3;</code>
     */
    @Override
    public int getExceptStatus() {
      return exceptStatus_;
    }

    public static final int LOAD_RATE_FIELD_NUMBER = 4;
    private double loadRate_;
    /**
     * <code>double load_rate = 4;</code>
     */
    @Override
    public double getLoadRate() {
      return loadRate_;
    }

    public static final int STERILIZE_STATUS_FIELD_NUMBER = 5;
    private int sterilizeStatus_;
    /**
     * <code>int32 sterilize_status = 5;</code>
     */
    @Override
    public int getSterilizeStatus() {
      return sterilizeStatus_;
    }

    public static final int ERROR_CODE_FIELD_NUMBER = 6;
    private java.util.List<Integer> errorCode_;
    /**
     * <code>repeated int32 error_code = 6;</code>
     */
    @Override
    public java.util.List<Integer>
        getErrorCodeList() {
      return errorCode_;
    }
    /**
     * <code>repeated int32 error_code = 6;</code>
     */
    @Override
    public int getErrorCodeCount() {
      return errorCode_.size();
    }
    /**
     * <code>repeated int32 error_code = 6;</code>
     */
    @Override
    public int getErrorCode(int index) {
      return errorCode_.get(index);
    }
    private int errorCodeMemoizedSerializedSize = -1;

    public static final int TEMPERATURE_FIELD_NUMBER = 7;
    private double temperature_;
    /**
     * <code>double temperature = 7;</code>
     */
    @Override
    public double getTemperature() {
      return temperature_;
    }

    public static final int TRACE_FIELD_NUMBER = 8;
    private int trace_;
    /**
     * <code>int32 trace = 8;</code>
     */
    @Override
    public int getTrace() {
      return trace_;
    }

    public static final int TOTAL_WEIGHT_FIELD_NUMBER = 9;
    private double totalWeight_;
    /**
     * <code>double total_weight = 9;</code>
     */
    @Override
    public double getTotalWeight() {
      return totalWeight_;
    }

    public static final int WORK_TYPE_FIELD_NUMBER = 10;
    private int workType_;
    /**
     * <code>int32 work_type = 10;</code>
     */
    @Override
    public int getWorkType() {
      return workType_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
          return true;
      }
      if (isInitialized == 0) {
          return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (boxStatus_ != 0) {
        output.writeInt32(1, boxStatus_);
      }
      if (type_ != 0) {
        output.writeInt32(2, type_);
      }
      if (exceptStatus_ != 0) {
        output.writeInt32(3, exceptStatus_);
      }
      if (loadRate_ != 0D) {
        output.writeDouble(4, loadRate_);
      }
      if (sterilizeStatus_ != 0) {
        output.writeInt32(5, sterilizeStatus_);
      }
      if (getErrorCodeList().size() > 0) {
        output.writeUInt32NoTag(50);
        output.writeUInt32NoTag(errorCodeMemoizedSerializedSize);
      }
      for (int i = 0; i < errorCode_.size(); i++) {
        output.writeInt32NoTag(errorCode_.get(i));
      }
      if (temperature_ != 0D) {
        output.writeDouble(7, temperature_);
      }
      if (trace_ != 0) {
        output.writeInt32(8, trace_);
      }
      if (totalWeight_ != 0D) {
        output.writeDouble(9, totalWeight_);
      }
      if (workType_ != 0) {
        output.writeInt32(10, workType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
          return size;
      }

      size = 0;
      if (boxStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, boxStatus_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (exceptStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, exceptStatus_);
      }
      if (loadRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, loadRate_);
      }
      if (sterilizeStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sterilizeStatus_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < errorCode_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(errorCode_.get(i));
        }
        size += dataSize;
        if (!getErrorCodeList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        errorCodeMemoizedSerializedSize = dataSize;
      }
      if (temperature_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, temperature_);
      }
      if (trace_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, trace_);
      }
      if (totalWeight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, totalWeight_);
      }
      if (workType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, workType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BoxStatus)) {
        return super.equals(obj);
      }
      BoxStatus other = (BoxStatus) obj;

      boolean result = true;
      result = result && (getBoxStatus()
          == other.getBoxStatus());
      result = result && (getType()
          == other.getType());
      result = result && (getExceptStatus()
          == other.getExceptStatus());
      result = result && (
          Double.doubleToLongBits(getLoadRate())
          == Double.doubleToLongBits(
              other.getLoadRate()));
      result = result && (getSterilizeStatus()
          == other.getSterilizeStatus());
      result = result && getErrorCodeList()
          .equals(other.getErrorCodeList());
      result = result && (
          Double.doubleToLongBits(getTemperature())
          == Double.doubleToLongBits(
              other.getTemperature()));
      result = result && (getTrace()
          == other.getTrace());
      result = result && (
          Double.doubleToLongBits(getTotalWeight())
          == Double.doubleToLongBits(
              other.getTotalWeight()));
      result = result && (getWorkType()
          == other.getWorkType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOX_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getBoxStatus();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + EXCEPT_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getExceptStatus();
      hash = (37 * hash) + LOAD_RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLoadRate()));
      hash = (37 * hash) + STERILIZE_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getSterilizeStatus();
      if (getErrorCodeCount() > 0) {
        hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorCodeList().hashCode();
      }
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getTemperature()));
      hash = (37 * hash) + TRACE_FIELD_NUMBER;
      hash = (53 * hash) + getTrace();
      hash = (37 * hash) + TOTAL_WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getTotalWeight()));
      hash = (37 * hash) + WORK_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getWorkType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BoxStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoxStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoxStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoxStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoxStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BoxStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BoxStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BoxStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BoxStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BoxStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BoxStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BoxStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BoxStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xhg.mqtt.proto.BoxStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xhg.mqtt.proto.BoxStatus)
        BoxStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BoxInfoPb.internal_static_com_xhg_mqtt_proto_BoxStatus_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BoxInfoPb.internal_static_com_xhg_mqtt_proto_BoxStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BoxStatus.class, Builder.class);
      }

      // Construct using com.xhg.mqtt.proto.BoxInfoPb.BoxStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        boxStatus_ = 0;

        type_ = 0;

        exceptStatus_ = 0;

        loadRate_ = 0D;

        sterilizeStatus_ = 0;

        errorCode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        temperature_ = 0D;

        trace_ = 0;

        totalWeight_ = 0D;

        workType_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BoxInfoPb.internal_static_com_xhg_mqtt_proto_BoxStatus_descriptor;
      }

      @Override
      public BoxStatus getDefaultInstanceForType() {
        return BoxStatus.getDefaultInstance();
      }

      @Override
      public BoxStatus build() {
        BoxStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public BoxStatus buildPartial() {
        BoxStatus result = new BoxStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.boxStatus_ = boxStatus_;
        result.type_ = type_;
        result.exceptStatus_ = exceptStatus_;
        result.loadRate_ = loadRate_;
        result.sterilizeStatus_ = sterilizeStatus_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          errorCode_ = java.util.Collections.unmodifiableList(errorCode_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.errorCode_ = errorCode_;
        result.temperature_ = temperature_;
        result.trace_ = trace_;
        result.totalWeight_ = totalWeight_;
        result.workType_ = workType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BoxStatus) {
          return mergeFrom((BoxStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BoxStatus other) {
        if (other == BoxStatus.getDefaultInstance()) {
            return this;
        }
        if (other.getBoxStatus() != 0) {
          setBoxStatus(other.getBoxStatus());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getExceptStatus() != 0) {
          setExceptStatus(other.getExceptStatus());
        }
        if (other.getLoadRate() != 0D) {
          setLoadRate(other.getLoadRate());
        }
        if (other.getSterilizeStatus() != 0) {
          setSterilizeStatus(other.getSterilizeStatus());
        }
        if (!other.errorCode_.isEmpty()) {
          if (errorCode_.isEmpty()) {
            errorCode_ = other.errorCode_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureErrorCodeIsMutable();
            errorCode_.addAll(other.errorCode_);
          }
          onChanged();
        }
        if (other.getTemperature() != 0D) {
          setTemperature(other.getTemperature());
        }
        if (other.getTrace() != 0) {
          setTrace(other.getTrace());
        }
        if (other.getTotalWeight() != 0D) {
          setTotalWeight(other.getTotalWeight());
        }
        if (other.getWorkType() != 0) {
          setWorkType(other.getWorkType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BoxStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BoxStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int boxStatus_ ;
      /**
       * <code>int32 box_status = 1;</code>
       */
      @Override
      public int getBoxStatus() {
        return boxStatus_;
      }
      /**
       * <code>int32 box_status = 1;</code>
       */
      public Builder setBoxStatus(int value) {
        
        boxStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 box_status = 1;</code>
       */
      public Builder clearBoxStatus() {
        
        boxStatus_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 2;</code>
       */
      @Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 2;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int exceptStatus_ ;
      /**
       * <code>int32 except_status = 3;</code>
       */
      @Override
      public int getExceptStatus() {
        return exceptStatus_;
      }
      /**
       * <code>int32 except_status = 3;</code>
       */
      public Builder setExceptStatus(int value) {
        
        exceptStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 except_status = 3;</code>
       */
      public Builder clearExceptStatus() {
        
        exceptStatus_ = 0;
        onChanged();
        return this;
      }

      private double loadRate_ ;
      /**
       * <code>double load_rate = 4;</code>
       */
      @Override
      public double getLoadRate() {
        return loadRate_;
      }
      /**
       * <code>double load_rate = 4;</code>
       */
      public Builder setLoadRate(double value) {
        
        loadRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double load_rate = 4;</code>
       */
      public Builder clearLoadRate() {
        
        loadRate_ = 0D;
        onChanged();
        return this;
      }

      private int sterilizeStatus_ ;
      /**
       * <code>int32 sterilize_status = 5;</code>
       */
      @Override
      public int getSterilizeStatus() {
        return sterilizeStatus_;
      }
      /**
       * <code>int32 sterilize_status = 5;</code>
       */
      public Builder setSterilizeStatus(int value) {
        
        sterilizeStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sterilize_status = 5;</code>
       */
      public Builder clearSterilizeStatus() {
        
        sterilizeStatus_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Integer> errorCode_ = java.util.Collections.emptyList();
      private void ensureErrorCodeIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          errorCode_ = new java.util.ArrayList<Integer>(errorCode_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated int32 error_code = 6;</code>
       */
      @Override
      public java.util.List<Integer>
          getErrorCodeList() {
        return java.util.Collections.unmodifiableList(errorCode_);
      }
      /**
       * <code>repeated int32 error_code = 6;</code>
       */
      @Override
      public int getErrorCodeCount() {
        return errorCode_.size();
      }
      /**
       * <code>repeated int32 error_code = 6;</code>
       */
      @Override
      public int getErrorCode(int index) {
        return errorCode_.get(index);
      }
      /**
       * <code>repeated int32 error_code = 6;</code>
       */
      public Builder setErrorCode(
          int index, int value) {
        ensureErrorCodeIsMutable();
        errorCode_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 error_code = 6;</code>
       */
      public Builder addErrorCode(int value) {
        ensureErrorCodeIsMutable();
        errorCode_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 error_code = 6;</code>
       */
      public Builder addAllErrorCode(
          Iterable<? extends Integer> values) {
        ensureErrorCodeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, errorCode_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 error_code = 6;</code>
       */
      public Builder clearErrorCode() {
        errorCode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      private double temperature_ ;
      /**
       * <code>double temperature = 7;</code>
       */
      @Override
      public double getTemperature() {
        return temperature_;
      }
      /**
       * <code>double temperature = 7;</code>
       */
      public Builder setTemperature(double value) {
        
        temperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double temperature = 7;</code>
       */
      public Builder clearTemperature() {
        
        temperature_ = 0D;
        onChanged();
        return this;
      }

      private int trace_ ;
      /**
       * <code>int32 trace = 8;</code>
       */
      @Override
      public int getTrace() {
        return trace_;
      }
      /**
       * <code>int32 trace = 8;</code>
       */
      public Builder setTrace(int value) {
        
        trace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 trace = 8;</code>
       */
      public Builder clearTrace() {
        
        trace_ = 0;
        onChanged();
        return this;
      }

      private double totalWeight_ ;
      /**
       * <code>double total_weight = 9;</code>
       */
      @Override
      public double getTotalWeight() {
        return totalWeight_;
      }
      /**
       * <code>double total_weight = 9;</code>
       */
      public Builder setTotalWeight(double value) {
        
        totalWeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double total_weight = 9;</code>
       */
      public Builder clearTotalWeight() {
        
        totalWeight_ = 0D;
        onChanged();
        return this;
      }

      private int workType_ ;
      /**
       * <code>int32 work_type = 10;</code>
       */
      @Override
      public int getWorkType() {
        return workType_;
      }
      /**
       * <code>int32 work_type = 10;</code>
       */
      public Builder setWorkType(int value) {
        
        workType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 work_type = 10;</code>
       */
      public Builder clearWorkType() {
        
        workType_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xhg.mqtt.proto.BoxStatus)
    }

    // @@protoc_insertion_point(class_scope:com.xhg.mqtt.proto.BoxStatus)
    private static final BoxStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BoxStatus();
    }

    public static BoxStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BoxStatus>
        PARSER = new com.google.protobuf.AbstractParser<BoxStatus>() {
      @Override
      public BoxStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BoxStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BoxStatus> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BoxStatus> getParserForType() {
      return PARSER;
    }

    @Override
    public BoxStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xhg_mqtt_proto_BoxInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xhg_mqtt_proto_BoxInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xhg_mqtt_proto_BoxStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xhg_mqtt_proto_BoxStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rBoxInfo.proto\022\022com.xhg.mqtt.proto\";\n\007B" +
      "oxInfo\0220\n\tboxStatus\030\001 \003(\0132\035.com.xhg.mqtt" +
      ".proto.BoxStatus\"\322\001\n\tBoxStatus\022\022\n\nbox_st" +
      "atus\030\001 \001(\005\022\014\n\004type\030\002 \001(\005\022\025\n\rexcept_statu" +
      "s\030\003 \001(\005\022\021\n\tload_rate\030\004 \001(\001\022\030\n\020sterilize_" +
      "status\030\005 \001(\005\022\022\n\nerror_code\030\006 \003(\005\022\023\n\013temp" +
      "erature\030\007 \001(\001\022\r\n\005trace\030\010 \001(\005\022\024\n\014total_we" +
      "ight\030\t \001(\001\022\021\n\twork_type\030\n \001(\005B\013B\tBoxInfo" +
      "Pbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          @Override
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xhg_mqtt_proto_BoxInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xhg_mqtt_proto_BoxInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xhg_mqtt_proto_BoxInfo_descriptor,
        new String[] { "BoxStatus", });
    internal_static_com_xhg_mqtt_proto_BoxStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xhg_mqtt_proto_BoxStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xhg_mqtt_proto_BoxStatus_descriptor,
        new String[] { "BoxStatus", "Type", "ExceptStatus", "LoadRate", "SterilizeStatus", "ErrorCode", "Temperature", "Trace", "TotalWeight", "WorkType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
