// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VersionInfo.proto

package com.xhg.mqtt.common.proto;

public final class VersionInfoPb {
  private VersionInfoPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VersionInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xhg.mqtt.proto.VersionInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
     */
    java.util.List<VersionStatus>
        getVersionStatusList();
    /**
     * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
     */
    VersionStatus getVersionStatus(int index);
    /**
     * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
     */
    int getVersionStatusCount();
    /**
     * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
     */
    java.util.List<? extends VersionStatusOrBuilder>
        getVersionStatusOrBuilderList();
    /**
     * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
     */
    VersionStatusOrBuilder getVersionStatusOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.xhg.mqtt.proto.VersionInfo}
   */
  public  static final class VersionInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xhg.mqtt.proto.VersionInfo)
      VersionInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VersionInfo.newBuilder() to construct.
    private VersionInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VersionInfo() {
      versionStatus_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VersionInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                versionStatus_ = new java.util.ArrayList<VersionStatus>();
                mutable_bitField0_ |= 0x00000001;
              }
              versionStatus_.add(
                  input.readMessage(VersionStatus.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          versionStatus_ = java.util.Collections.unmodifiableList(versionStatus_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VersionInfoPb.internal_static_com_xhg_mqtt_proto_VersionInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VersionInfoPb.internal_static_com_xhg_mqtt_proto_VersionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VersionInfo.class, Builder.class);
    }

    public static final int VERSIONSTATUS_FIELD_NUMBER = 1;
    private java.util.List<VersionStatus> versionStatus_;
    /**
     * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
     */
    public java.util.List<VersionStatus> getVersionStatusList() {
      return versionStatus_;
    }
    /**
     * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
     */
    public java.util.List<? extends VersionStatusOrBuilder>
        getVersionStatusOrBuilderList() {
      return versionStatus_;
    }
    /**
     * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
     */
    public int getVersionStatusCount() {
      return versionStatus_.size();
    }
    /**
     * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
     */
    public VersionStatus getVersionStatus(int index) {
      return versionStatus_.get(index);
    }
    /**
     * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
     */
    public VersionStatusOrBuilder getVersionStatusOrBuilder(
        int index) {
      return versionStatus_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < versionStatus_.size(); i++) {
        output.writeMessage(1, versionStatus_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < versionStatus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, versionStatus_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof VersionInfo)) {
        return super.equals(obj);
      }
      VersionInfo other = (VersionInfo) obj;

      boolean result = true;
      result = result && getVersionStatusList()
          .equals(other.getVersionStatusList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getVersionStatusCount() > 0) {
        hash = (37 * hash) + VERSIONSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getVersionStatusList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static VersionInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VersionInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VersionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VersionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VersionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VersionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VersionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VersionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static VersionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static VersionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static VersionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VersionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(VersionInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xhg.mqtt.proto.VersionInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xhg.mqtt.proto.VersionInfo)
        VersionInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return VersionInfoPb.internal_static_com_xhg_mqtt_proto_VersionInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return VersionInfoPb.internal_static_com_xhg_mqtt_proto_VersionInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VersionInfo.class, Builder.class);
      }

      // Construct using com.xhg.mqtt.proto.VersionInfoPb.VersionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVersionStatusFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (versionStatusBuilder_ == null) {
          versionStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          versionStatusBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return VersionInfoPb.internal_static_com_xhg_mqtt_proto_VersionInfo_descriptor;
      }

      @Override
      public VersionInfo getDefaultInstanceForType() {
        return VersionInfo.getDefaultInstance();
      }

      @Override
      public VersionInfo build() {
        VersionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public VersionInfo buildPartial() {
        VersionInfo result = new VersionInfo(this);
        int from_bitField0_ = bitField0_;
        if (versionStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            versionStatus_ = java.util.Collections.unmodifiableList(versionStatus_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.versionStatus_ = versionStatus_;
        } else {
          result.versionStatus_ = versionStatusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VersionInfo) {
          return mergeFrom((VersionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VersionInfo other) {
        if (other == VersionInfo.getDefaultInstance()) return this;
        if (versionStatusBuilder_ == null) {
          if (!other.versionStatus_.isEmpty()) {
            if (versionStatus_.isEmpty()) {
              versionStatus_ = other.versionStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureVersionStatusIsMutable();
              versionStatus_.addAll(other.versionStatus_);
            }
            onChanged();
          }
        } else {
          if (!other.versionStatus_.isEmpty()) {
            if (versionStatusBuilder_.isEmpty()) {
              versionStatusBuilder_.dispose();
              versionStatusBuilder_ = null;
              versionStatus_ = other.versionStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
              versionStatusBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getVersionStatusFieldBuilder() : null;
            } else {
              versionStatusBuilder_.addAllMessages(other.versionStatus_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        VersionInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (VersionInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<VersionStatus> versionStatus_ =
        java.util.Collections.emptyList();
      private void ensureVersionStatusIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          versionStatus_ = new java.util.ArrayList<VersionStatus>(versionStatus_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          VersionStatus, VersionStatus.Builder, VersionStatusOrBuilder> versionStatusBuilder_;

      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public java.util.List<VersionStatus> getVersionStatusList() {
        if (versionStatusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(versionStatus_);
        } else {
          return versionStatusBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public int getVersionStatusCount() {
        if (versionStatusBuilder_ == null) {
          return versionStatus_.size();
        } else {
          return versionStatusBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public VersionStatus getVersionStatus(int index) {
        if (versionStatusBuilder_ == null) {
          return versionStatus_.get(index);
        } else {
          return versionStatusBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public Builder setVersionStatus(
          int index, VersionStatus value) {
        if (versionStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVersionStatusIsMutable();
          versionStatus_.set(index, value);
          onChanged();
        } else {
          versionStatusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public Builder setVersionStatus(
          int index, VersionStatus.Builder builderForValue) {
        if (versionStatusBuilder_ == null) {
          ensureVersionStatusIsMutable();
          versionStatus_.set(index, builderForValue.build());
          onChanged();
        } else {
          versionStatusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public Builder addVersionStatus(VersionStatus value) {
        if (versionStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVersionStatusIsMutable();
          versionStatus_.add(value);
          onChanged();
        } else {
          versionStatusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public Builder addVersionStatus(
          int index, VersionStatus value) {
        if (versionStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVersionStatusIsMutable();
          versionStatus_.add(index, value);
          onChanged();
        } else {
          versionStatusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public Builder addVersionStatus(
          VersionStatus.Builder builderForValue) {
        if (versionStatusBuilder_ == null) {
          ensureVersionStatusIsMutable();
          versionStatus_.add(builderForValue.build());
          onChanged();
        } else {
          versionStatusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public Builder addVersionStatus(
          int index, VersionStatus.Builder builderForValue) {
        if (versionStatusBuilder_ == null) {
          ensureVersionStatusIsMutable();
          versionStatus_.add(index, builderForValue.build());
          onChanged();
        } else {
          versionStatusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public Builder addAllVersionStatus(
          Iterable<? extends VersionStatus> values) {
        if (versionStatusBuilder_ == null) {
          ensureVersionStatusIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, versionStatus_);
          onChanged();
        } else {
          versionStatusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public Builder clearVersionStatus() {
        if (versionStatusBuilder_ == null) {
          versionStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          versionStatusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public Builder removeVersionStatus(int index) {
        if (versionStatusBuilder_ == null) {
          ensureVersionStatusIsMutable();
          versionStatus_.remove(index);
          onChanged();
        } else {
          versionStatusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public VersionStatus.Builder getVersionStatusBuilder(
          int index) {
        return getVersionStatusFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public VersionStatusOrBuilder getVersionStatusOrBuilder(
          int index) {
        if (versionStatusBuilder_ == null) {
          return versionStatus_.get(index);  } else {
          return versionStatusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public java.util.List<? extends VersionStatusOrBuilder>
           getVersionStatusOrBuilderList() {
        if (versionStatusBuilder_ != null) {
          return versionStatusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(versionStatus_);
        }
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public VersionStatus.Builder addVersionStatusBuilder() {
        return getVersionStatusFieldBuilder().addBuilder(
            VersionStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public VersionStatus.Builder addVersionStatusBuilder(
          int index) {
        return getVersionStatusFieldBuilder().addBuilder(
            index, VersionStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .com.xhg.mqtt.proto.VersionStatus versionStatus = 1;</code>
       */
      public java.util.List<VersionStatus.Builder>
           getVersionStatusBuilderList() {
        return getVersionStatusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          VersionStatus, VersionStatus.Builder, VersionStatusOrBuilder>
          getVersionStatusFieldBuilder() {
        if (versionStatusBuilder_ == null) {
          versionStatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              VersionStatus, VersionStatus.Builder, VersionStatusOrBuilder>(
                  versionStatus_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          versionStatus_ = null;
        }
        return versionStatusBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xhg.mqtt.proto.VersionInfo)
    }

    // @@protoc_insertion_point(class_scope:com.xhg.mqtt.proto.VersionInfo)
    private static final VersionInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new VersionInfo();
    }

    public static VersionInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VersionInfo>
        PARSER = new com.google.protobuf.AbstractParser<VersionInfo>() {
      @Override
      public VersionInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VersionInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VersionInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VersionInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public VersionInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VersionStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xhg.mqtt.proto.VersionStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 type = 1;</code>
     */
    int getType();

    /**
     * <code>int32 box_type = 2;</code>
     */
    int getBoxType();

    /**
     * <code>string version = 3;</code>
     */
    String getVersion();
    /**
     * <code>string version = 3;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>int32 status = 4;</code>
     */
    int getStatus();

    /**
     * <code>string status_desc = 5;</code>
     */
    String getStatusDesc();
    /**
     * <code>string status_desc = 5;</code>
     */
    com.google.protobuf.ByteString
        getStatusDescBytes();
  }
  /**
   * Protobuf type {@code com.xhg.mqtt.proto.VersionStatus}
   */
  public  static final class VersionStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xhg.mqtt.proto.VersionStatus)
      VersionStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VersionStatus.newBuilder() to construct.
    private VersionStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VersionStatus() {
      type_ = 0;
      boxType_ = 0;
      version_ = "";
      status_ = 0;
      statusDesc_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VersionStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 16: {

              boxType_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 32: {

              status_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              statusDesc_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VersionInfoPb.internal_static_com_xhg_mqtt_proto_VersionStatus_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VersionInfoPb.internal_static_com_xhg_mqtt_proto_VersionStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VersionStatus.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int BOX_TYPE_FIELD_NUMBER = 2;
    private int boxType_;
    /**
     * <code>int32 box_type = 2;</code>
     */
    public int getBoxType() {
      return boxType_;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private volatile Object version_;
    /**
     * <code>string version = 3;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>int32 status = 4;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int STATUS_DESC_FIELD_NUMBER = 5;
    private volatile Object statusDesc_;
    /**
     * <code>string status_desc = 5;</code>
     */
    public String getStatusDesc() {
      Object ref = statusDesc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        statusDesc_ = s;
        return s;
      }
    }
    /**
     * <code>string status_desc = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStatusDescBytes() {
      Object ref = statusDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        statusDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (boxType_ != 0) {
        output.writeInt32(2, boxType_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, version_);
      }
      if (status_ != 0) {
        output.writeInt32(4, status_);
      }
      if (!getStatusDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, statusDesc_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (boxType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, boxType_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, version_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, status_);
      }
      if (!getStatusDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, statusDesc_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof VersionStatus)) {
        return super.equals(obj);
      }
      VersionStatus other = (VersionStatus) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && (getBoxType()
          == other.getBoxType());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && (getStatus()
          == other.getStatus());
      result = result && getStatusDesc()
          .equals(other.getStatusDesc());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + BOX_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBoxType();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + STATUS_DESC_FIELD_NUMBER;
      hash = (53 * hash) + getStatusDesc().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static VersionStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VersionStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VersionStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VersionStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VersionStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VersionStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VersionStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VersionStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static VersionStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static VersionStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static VersionStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VersionStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(VersionStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xhg.mqtt.proto.VersionStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xhg.mqtt.proto.VersionStatus)
        VersionStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return VersionInfoPb.internal_static_com_xhg_mqtt_proto_VersionStatus_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return VersionInfoPb.internal_static_com_xhg_mqtt_proto_VersionStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VersionStatus.class, Builder.class);
      }

      // Construct using com.xhg.mqtt.proto.VersionInfoPb.VersionStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        boxType_ = 0;

        version_ = "";

        status_ = 0;

        statusDesc_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return VersionInfoPb.internal_static_com_xhg_mqtt_proto_VersionStatus_descriptor;
      }

      @Override
      public VersionStatus getDefaultInstanceForType() {
        return VersionStatus.getDefaultInstance();
      }

      @Override
      public VersionStatus build() {
        VersionStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public VersionStatus buildPartial() {
        VersionStatus result = new VersionStatus(this);
        result.type_ = type_;
        result.boxType_ = boxType_;
        result.version_ = version_;
        result.status_ = status_;
        result.statusDesc_ = statusDesc_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VersionStatus) {
          return mergeFrom((VersionStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VersionStatus other) {
        if (other == VersionStatus.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getBoxType() != 0) {
          setBoxType(other.getBoxType());
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getStatusDesc().isEmpty()) {
          statusDesc_ = other.statusDesc_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        VersionStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (VersionStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int boxType_ ;
      /**
       * <code>int32 box_type = 2;</code>
       */
      public int getBoxType() {
        return boxType_;
      }
      /**
       * <code>int32 box_type = 2;</code>
       */
      public Builder setBoxType(int value) {
        
        boxType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 box_type = 2;</code>
       */
      public Builder clearBoxType() {
        
        boxType_ = 0;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <code>string version = 3;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string version = 3;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 3;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 3;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 3;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 4;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 4;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private Object statusDesc_ = "";
      /**
       * <code>string status_desc = 5;</code>
       */
      public String getStatusDesc() {
        Object ref = statusDesc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          statusDesc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string status_desc = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStatusDescBytes() {
        Object ref = statusDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          statusDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status_desc = 5;</code>
       */
      public Builder setStatusDesc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        statusDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status_desc = 5;</code>
       */
      public Builder clearStatusDesc() {
        
        statusDesc_ = getDefaultInstance().getStatusDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string status_desc = 5;</code>
       */
      public Builder setStatusDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        statusDesc_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xhg.mqtt.proto.VersionStatus)
    }

    // @@protoc_insertion_point(class_scope:com.xhg.mqtt.proto.VersionStatus)
    private static final VersionStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new VersionStatus();
    }

    public static VersionStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VersionStatus>
        PARSER = new com.google.protobuf.AbstractParser<VersionStatus>() {
      @Override
      public VersionStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VersionStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VersionStatus> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VersionStatus> getParserForType() {
      return PARSER;
    }

    @Override
    public VersionStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xhg_mqtt_proto_VersionInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xhg_mqtt_proto_VersionInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xhg_mqtt_proto_VersionStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xhg_mqtt_proto_VersionStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021VersionInfo.proto\022\022com.xhg.mqtt.proto\"" +
      "G\n\013VersionInfo\0228\n\rversionStatus\030\001 \003(\0132!." +
      "com.xhg.mqtt.proto.VersionStatus\"e\n\rVers" +
      "ionStatus\022\014\n\004type\030\001 \001(\005\022\020\n\010box_type\030\002 \001(" +
      "\005\022\017\n\007version\030\003 \001(\t\022\016\n\006status\030\004 \001(\005\022\023\n\013st" +
      "atus_desc\030\005 \001(\tB\017B\rVersionInfoPbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xhg_mqtt_proto_VersionInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xhg_mqtt_proto_VersionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xhg_mqtt_proto_VersionInfo_descriptor,
        new String[] { "VersionStatus", });
    internal_static_com_xhg_mqtt_proto_VersionStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xhg_mqtt_proto_VersionStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xhg_mqtt_proto_VersionStatus_descriptor,
        new String[] { "Type", "BoxType", "Version", "Status", "StatusDesc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
