// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SiteInfo.proto

package com.xie.mqtt.common.proto;

public final class SiteInfoPb {
  private SiteInfoPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SiteInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xhg.mqtt.proto.SiteInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint64 restart_time = 1;</code>
     */
    long getRestartTime();

    /**
     * <pre>
     * 温度状态 0正常 1高温预警
     * </pre>
     *
     * <code>int32 temp_status = 2;</code>
     */
    int getTempStatus();

    /**
     * <pre>
     * 站点状态 1上线 2下线
     * </pre>
     *
     * <code>int32 status = 3;</code>
     */
    int getStatus();

    /**
     * <pre>
     * 是否有追溯功能 0没有 1有
     * </pre>
     *
     * <code>int32 trace = 4;</code>
     */
    int getTrace();
  }
  /**
   * Protobuf type {@code com.xhg.mqtt.proto.SiteInfo}
   */
  public  static final class SiteInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xhg.mqtt.proto.SiteInfo)
      SiteInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SiteInfo.newBuilder() to construct.
    private SiteInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SiteInfo() {
      restartTime_ = 0L;
      tempStatus_ = 0;
      status_ = 0;
      trace_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SiteInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              restartTime_ = input.readSInt64();
              break;
            }
            case 16: {

              tempStatus_ = input.readInt32();
              break;
            }
            case 24: {

              status_ = input.readInt32();
              break;
            }
            case 32: {

              trace_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SiteInfoPb.internal_static_com_xhg_mqtt_proto_SiteInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SiteInfoPb.internal_static_com_xhg_mqtt_proto_SiteInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SiteInfo.class, Builder.class);
    }

    public static final int RESTART_TIME_FIELD_NUMBER = 1;
    private long restartTime_;
    /**
     * <code>sint64 restart_time = 1;</code>
     */
    public long getRestartTime() {
      return restartTime_;
    }

    public static final int TEMP_STATUS_FIELD_NUMBER = 2;
    private int tempStatus_;
    /**
     * <pre>
     * 温度状态 0正常 1高温预警
     * </pre>
     *
     * <code>int32 temp_status = 2;</code>
     */
    public int getTempStatus() {
      return tempStatus_;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <pre>
     * 站点状态 1上线 2下线
     * </pre>
     *
     * <code>int32 status = 3;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int TRACE_FIELD_NUMBER = 4;
    private int trace_;
    /**
     * <pre>
     * 是否有追溯功能 0没有 1有
     * </pre>
     *
     * <code>int32 trace = 4;</code>
     */
    public int getTrace() {
      return trace_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (restartTime_ != 0L) {
        output.writeSInt64(1, restartTime_);
      }
      if (tempStatus_ != 0) {
        output.writeInt32(2, tempStatus_);
      }
      if (status_ != 0) {
        output.writeInt32(3, status_);
      }
      if (trace_ != 0) {
        output.writeInt32(4, trace_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (restartTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, restartTime_);
      }
      if (tempStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, tempStatus_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      if (trace_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, trace_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SiteInfo)) {
        return super.equals(obj);
      }
      SiteInfo other = (SiteInfo) obj;

      boolean result = true;
      result = result && (getRestartTime()
          == other.getRestartTime());
      result = result && (getTempStatus()
          == other.getTempStatus());
      result = result && (getStatus()
          == other.getStatus());
      result = result && (getTrace()
          == other.getTrace());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESTART_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRestartTime());
      hash = (37 * hash) + TEMP_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getTempStatus();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + TRACE_FIELD_NUMBER;
      hash = (53 * hash) + getTrace();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SiteInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SiteInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SiteInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SiteInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SiteInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SiteInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SiteInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SiteInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SiteInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SiteInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SiteInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SiteInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SiteInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xhg.mqtt.proto.SiteInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xhg.mqtt.proto.SiteInfo)
        SiteInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SiteInfoPb.internal_static_com_xhg_mqtt_proto_SiteInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SiteInfoPb.internal_static_com_xhg_mqtt_proto_SiteInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SiteInfo.class, Builder.class);
      }

      // Construct using com.xhg.mqtt.proto.SiteInfoPb.SiteInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        restartTime_ = 0L;

        tempStatus_ = 0;

        status_ = 0;

        trace_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SiteInfoPb.internal_static_com_xhg_mqtt_proto_SiteInfo_descriptor;
      }

      @Override
      public SiteInfo getDefaultInstanceForType() {
        return SiteInfo.getDefaultInstance();
      }

      @Override
      public SiteInfo build() {
        SiteInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SiteInfo buildPartial() {
        SiteInfo result = new SiteInfo(this);
        result.restartTime_ = restartTime_;
        result.tempStatus_ = tempStatus_;
        result.status_ = status_;
        result.trace_ = trace_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SiteInfo) {
          return mergeFrom((SiteInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SiteInfo other) {
        if (other == SiteInfo.getDefaultInstance()) return this;
        if (other.getRestartTime() != 0L) {
          setRestartTime(other.getRestartTime());
        }
        if (other.getTempStatus() != 0) {
          setTempStatus(other.getTempStatus());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (other.getTrace() != 0) {
          setTrace(other.getTrace());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SiteInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SiteInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long restartTime_ ;
      /**
       * <code>sint64 restart_time = 1;</code>
       */
      public long getRestartTime() {
        return restartTime_;
      }
      /**
       * <code>sint64 restart_time = 1;</code>
       */
      public Builder setRestartTime(long value) {
        
        restartTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 restart_time = 1;</code>
       */
      public Builder clearRestartTime() {
        
        restartTime_ = 0L;
        onChanged();
        return this;
      }

      private int tempStatus_ ;
      /**
       * <pre>
       * 温度状态 0正常 1高温预警
       * </pre>
       *
       * <code>int32 temp_status = 2;</code>
       */
      public int getTempStatus() {
        return tempStatus_;
      }
      /**
       * <pre>
       * 温度状态 0正常 1高温预警
       * </pre>
       *
       * <code>int32 temp_status = 2;</code>
       */
      public Builder setTempStatus(int value) {
        
        tempStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 温度状态 0正常 1高温预警
       * </pre>
       *
       * <code>int32 temp_status = 2;</code>
       */
      public Builder clearTempStatus() {
        
        tempStatus_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <pre>
       * 站点状态 1上线 2下线
       * </pre>
       *
       * <code>int32 status = 3;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 站点状态 1上线 2下线
       * </pre>
       *
       * <code>int32 status = 3;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 站点状态 1上线 2下线
       * </pre>
       *
       * <code>int32 status = 3;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private int trace_ ;
      /**
       * <pre>
       * 是否有追溯功能 0没有 1有
       * </pre>
       *
       * <code>int32 trace = 4;</code>
       */
      public int getTrace() {
        return trace_;
      }
      /**
       * <pre>
       * 是否有追溯功能 0没有 1有
       * </pre>
       *
       * <code>int32 trace = 4;</code>
       */
      public Builder setTrace(int value) {
        
        trace_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否有追溯功能 0没有 1有
       * </pre>
       *
       * <code>int32 trace = 4;</code>
       */
      public Builder clearTrace() {
        
        trace_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xhg.mqtt.proto.SiteInfo)
    }

    // @@protoc_insertion_point(class_scope:com.xhg.mqtt.proto.SiteInfo)
    private static final SiteInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SiteInfo();
    }

    public static SiteInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SiteInfo>
        PARSER = new com.google.protobuf.AbstractParser<SiteInfo>() {
      @Override
      public SiteInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SiteInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SiteInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SiteInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public SiteInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xhg_mqtt_proto_SiteInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xhg_mqtt_proto_SiteInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016SiteInfo.proto\022\022com.xhg.mqtt.proto\"T\n\010" +
      "SiteInfo\022\024\n\014restart_time\030\001 \001(\022\022\023\n\013temp_s" +
      "tatus\030\002 \001(\005\022\016\n\006status\030\003 \001(\005\022\r\n\005trace\030\004 \001" +
      "(\005B\014B\nSiteInfoPbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xhg_mqtt_proto_SiteInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xhg_mqtt_proto_SiteInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xhg_mqtt_proto_SiteInfo_descriptor,
        new String[] { "RestartTime", "TempStatus", "Status", "Trace", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
